#
# pyproject.toml
#

import dataclasses
import re
from typing import Dict, List, Optional

_arch_re = re.compile(r"\{\{\s*ARCH\s*\}\}")
_os_re = re.compile(r"\{\{\s*OS\s*\}\}")


@dataclasses.dataclass
class TypeCasterConfig:
    """
    Specifies type casters that this package exports. robotpy-build
    will attempt to detect these types at generation time and include
    them in generated wrappers.

    .. code-block:: toml

       [[tool.robotpy-build.wrappers."PACKAGENAME".type_casters]]
       header = "my_type_caster.h"
       types = ["foo_t", "ns::ins::bar_t"]

    .. seealso:: :ref:`type_casters`
    """

    #: Header file to include when one of the types are detected in a wrapper
    header: str

    #: Types to look for to indicate that this type caster header should be
    #: included.
    types: List[str]

    #: If a parameter type that requires this type caster requires a default
    #: argument, a C-style ``(type)`` cast is used on the default argument.
    #:
    #: The default cast can be disabled via param_override's ``disable_type_caster_default_cast``
    default_arg_cast: bool = False


@dataclasses.dataclass
class ModuleConfig:
    """
    Configuration for generating pybind11 wrappers around specified header files.
    The
    """

    #: Name that other projects/wrappers use in their 'depends' list
    name: str

    #: Name of generated file that ensures the shared libraries and any
    #: dependencies are loaded. Defaults to ``_init_{name}.py``
    #:
    #: Generally, you should create an ``__init__.py`` file that imports
    #: this module, otherwise your users will need to do so.
    libinit: Optional[str] = None

    #: Name of pkgconf libraries that this is wrapping. This is also added to
    #: depends list.
    wraps: List[str] = []

    #: List of pkgconf library dependencies. This affects this wrapper
    #: library in the following ways:
    #:
    #: * Any include file directories exported by the dependency will be added
    #:   to the include path for any source files compiled by this wrapper
    #: * It will be linked to any libraries the dependency contains
    #: * The python module for the dependency will be imported in the
    #:   ``_init{extension}.py`` file.
    depends: List[str] = dataclasses.field(default_factory=list)

    #: List of extra include directories to export, relative to the
    #: project root.
    extra_includes: List[str] = dataclasses.field(default_factory=list)

    # #: Optional source files to compile. Path is relative to the root of
    # #: the project.
    # sources: List[str] = dataclasses.field(default_factory=list)

    #: Specifies header files that autogenerated pybind11 wrappers will be
    #: created for. Simple C++ headers will most likely 'just work', but
    #: complex headers will need to have an accompanying :attr:`generation_data`
    #: file specified that can customize the autogenerated files.
    #:
    #: List of dictionaries: each dictionary key is used for the function
    #: name of the initialization function, the value is the header that is
    #: being wrapped. The header is first looked for relative to the
    #: package, then relative to each include directory (including
    #: downloaded and extracted packages).
    #:
    #: .. code-block:: toml
    #:
    #:    [tool.robotpy-build.wrappers."PACKAGENAME".headers]
    #:    Name = "header.h"
    #:
    #: .. seealso:: :ref:`autowrap`
    #:
    headers: Dict[str, str] = {}

    #: Path to a directory of yaml files. Generation data will be looked up
    #: using the key in the generate dictionary.
    #:
    #: These YAML files can be generated via the robotpy-build command line tool:
    #:
    #: .. code-block:: sh
    #:
    #:    robotpy-build create-gen --write
    #:
    #: .. seealso:: :ref:`gendata`
    #:
    yaml_path: Optional[str] = None

    #: Specifies type casters that this package exports.
    type_casters: List[TypeCasterConfig] = dataclasses.field(default_factory=list)

    #: Preprocessor definitions to apply when compiling this wrapper.
    pp_defines: List[str] = dataclasses.field(default_factory=list)

    #: If True, skip this wrapper; typically used in conjection with an override.
    ignore: bool = False


@dataclasses.dataclass
class SemiwrapToolConfig:
    """
    Contains information for configuring the project

    .. code-block:: toml

       [tool.semiwrap]

    .. note:: This section is required
    """

    #: List of headers for the scan-headers tool to ignore
    scan_headers_ignore: List[str] = dataclasses.field(default_factory=list)

    #: List of python packages with __init__.py to update when ``python setup.py update_init``
    #: is called -- this is an argument to the ``robotpy-build create-imports`` command, and
    #: may contain a space and the second argument to create-imports.
    # update_init: List[str] = []

    #: Modules to autogenerate. The key is the python package name
    #: that the module will live in
    modules: Dict[str, ModuleConfig] = dataclasses.field(default_factory=dict)


@dataclasses.dataclass
class SemiwrapHatchlingConfig:
    """
    semiwrap hatchling hook configuration

    .. code-block:: toml

       [tool.hatch.build.hooks.semiwrap]

    .. note:: This section is required
    """

    #: Output directory to write meson.build to
    autogen_build_path: str = "wrapcfg"

    #: Output directory to write second stage meson.build to (defaults
    #: to autogen_build_path / 'modules')
    module_build_path: Optional[str] = None
