"""
Generates a file that loads shared library dependencies for the module

Arguments: pyproject.toml package.name /path/to/_init_name.py
"""

from __future__ import annotations

import inspect
import pathlib
import platform
import sys
import typing as T

from .autowrap.buffer import RenderBuffer
from .pyproject import PyProject
from .util import maybe_write_file

platform_sys = platform.system()
is_windows = platform_sys == "Windows"
is_macos = platform_sys == "Darwin"


# TODO: this belongs in a separate script/api that can be used from multiple tools
# .. maybe in dynamic-library
def _write_libinit_py(
    project: PyProject,
    init_py: pathlib.Path,
    libs: T.List[pathlib.Path],
    requires: T.List[str],
):
    """
    :param init_py: the _init module for the library(ies) that is written out
    :param libs: for each library that is being initialized, this is the
                 path to that library

    :param requires: other pkgconf packages that these libraries depend on.
                     Their init_py will be looked up and imported first.
    """

    platform = project.platform
    r = RenderBuffer()

    r.writeln("# This file is automatically generated, DO NOT EDIT")
    r.writeln("# fmt: off")
    r.writeln()

    need_space = False
    for req in requires:
        module = project.pkgconf.get(req).libinit_py
        if module:
            r.writeln(f"import {module}")
            need_space = True

    if need_space:
        r.writeln()

    # TODO: don't need this?

    # if libs:
    #     r.writeln("def __load_library():")

    #     with r.indent(4):

    #         r.writeln("from os.path import abspath, join, dirname, exists")
    #         if platform.os == "osx":
    #             r.writeln("from ctypes import CDLL, RTLD_GLOBAL")
    #         else:
    #             r.writeln("from ctypes import cdll")

    #         r.writeln()

    #         r.writeln("root = abspath(dirname(__file__))")
    #         r.writeln("libs = []")

    #         for lib in libs:
    #             rel = lib.relative_to(init_py.parent)
    #             components = ", ".join(map(repr, rel.parts))

    #             r.writeln(f"lib_path = join(root, {components})")

    #             r.writeln("try:")
    #             with r.indent(4):
    #                 if platform.os == "osx":
    #                     r.writeln(f"libs += [CDLL(lib_path, mode=RTLD_GLOBAL)]")
    #                 else:
    #                     r.writeln("libs += [cdll.LoadLibrary(lib_path)]")

    #             r.writeln("except FileNotFoundError:")
    #             with r.indent(4):
    #                 r.writeln("if not exists(lib_path):")
    #                 r.writeln(
    #                     f'    raise FileNotFoundError("{lib.name} was not found on your system. Is this package correctly installed?")'
    #                 )
    #             if platform.os == "windows":
    #                 r.writeln(
    #                     f'raise Exception("{lib.name} could not be loaded. Do you have Visual Studio C++ Redistributible 2019 installed?")'
    #                 )
    #             else:
    #                 r.writeln(
    #                     f'raise FileNotFoundError("{lib.name} could not be loaded. There is a missing dependency.")'
    #                 )

    #             r.writeln()

    #         r.writeln("return libs")

    #     r.writeln()
    #     r.writeln("__libs = __load_library()")
    #     r.writeln()

    maybe_write_file(init_py, r.getvalue())


def main():
    try:
        _, pyproject_toml, package_name, libinit_py = sys.argv
    except ValueError:
        print(inspect.cleandoc(__doc__ or ""), file=sys.stderr)
        sys.exit(1)

    pyproject = PyProject(pathlib.Path(pyproject_toml))

    module = pyproject.get_module(package_name)
    depends = pyproject.get_module_deps(module)

    # TODO: libs
    # .. oh, those were going to get created by the downloader hatch plugin
    #    so we don't need them? maybe
    libs = []

    # need os, dependencies, section name
    _write_libinit_py(
        pyproject,
        pathlib.Path(libinit_py),
        libs,
        depends,
    )


if __name__ == "__main__":
    main()
